pipeline {
    agent { label 'docker-host' }

    triggers {
        pollSCM('H/5 * * * *')
    }

    environment {
        DOCKER_IMAGE = "leer:${BUILD_NUMBER}"
        DOCKER_REGISTRY = "fairygel"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'fetching github repo...'
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'building docker image...'
                script {
                    sh 'cd ${WORKSPACE}/backend && docker build -t ${DOCKER_IMAGE} .'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                echo 'pushing docker image to Docker Hub...'
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker_hub_credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh '''
                            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                            docker tag ${DOCKER_IMAGE} ${DOCKER_REGISTRY}/leer:latest
                            docker push ${DOCKER_REGISTRY}/leer:latest
                            docker logout
                        '''
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'deploying via ssh...'
                sshagent(['ssh_key_credentials']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no masotto@172.26.253.138 "
                            cd /home/masotto/leer && \
                            docker pull ${DOCKER_REGISTRY}/leer:latest && \
                            docker compose down && \
                            docker compose up -d
                        "
                    '''
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo '✅ Pipeline success!'
        }
        failure {
            echo '❌ Pipeline exited with error!'
        }
    }
}